---
services:
  postgres:
    image: "postgres:15-alpine"
    environment:
      POSTGRES_DB: formance
      POSTGRES_USER: formance
      POSTGRES_PASSWORD: formance
    ports:
      - "${FORMANCE_POSTGRES_PORT:-5432}:5432"
    volumes:
      - "postgres_data:/var/lib/postgresql/data"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U formance -d formance"]
      interval: 10s
      timeout: 5s
      retries: 5
    restart: unless-stopped

volumes:
  postgres_data: